# -*- coding: utf-8 -*-
"""Quantum classifier.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PAalG0FL4d5-Cgic605B9o-6VJHPWOGz
"""

!pip uninstall -y fitz PyMuPDF
!pip install --no-cache-dir PyMuPDF

!pip install --no-cache-dir PyMuPDF
import fitz
print("PyMuPDF version:", fitz.__doc__ or "Loaded")
print("fitz has open():", hasattr(fitz, "open"))

from datasets import load_dataset

dataset = load_dataset("vihaannnn/Indian-Supreme-Court-Judgements-Chunked")
print(dataset)
print(dataset["train"][0])

from datasets import load_dataset
dataset = load_dataset("lex_glue", "ecthr_a")
print(dataset["train"][0])

"""
Quantum Legal-NLP Experiment (Colab-ready, with automatic dataset fallback)
Adapted for: Colab, English, Legal-GPT, simple quantum simulation

This version automatically falls back to the Hugging Face dataset 'vihaannnn/Indian-Supreme-Court-Judgements-Chunked'
if AWS Open Data (Indian High Court Judgments) is unavailable.
"""

# ==============
# 1) Install dependencies (Colab-friendly)
# ==============
!pip uninstall -y fitz PyMuPDF -q
!pip install --no-cache-dir PyMuPDF -q
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 -q
!pip install awscli boto3 pyarrow transformers[sentencepiece] pdfplumber tqdm datasets matplotlib -q

import os, zipfile, glob, fitz, json, math, re, torch
import matplotlib.pyplot as plt
from tqdm.auto import tqdm
from transformers import AutoTokenizer, AutoModelForCausalLM
from datasets import load_dataset

# ==============
# 2) Try to fetch Indian High Court judgments from AWS, else fallback
# ==============

os.makedirs('data_pdfs', exist_ok=True)
os.makedirs('data_text', exist_ok=True)

try:
    print('Attempting to list AWS Open Data bucket...')
    !aws s3 ls s3://indian-high-court-judgments/data/zip/ --no-sign-request | head -n 5
    !aws s3 cp s3://indian-high-court-judgments/data/zip/year=2023/english_part1.zip ./english_2023_part1.zip --no-sign-request
    if os.path.exists('english_2023_part1.zip'):
        with zipfile.ZipFile('english_2023_part1.zip', 'r') as z:
            z.extractall('data_pdfs')
        print('✅ Extracted AWS dataset into data_pdfs/')
    else:
        raise Exception('AWS zip not found, switching to fallback dataset.')
except Exception as e:
    print('\n⚠️ AWS dataset not accessible, switching to Hugging Face fallback...')
    dataset = load_dataset('vihaannnn/Indian-Supreme-Court-Judgements-Chunked', split='train[:200]')
    corpus = [r['text'] for r in dataset]
    os.makedirs('data_text', exist_ok=True)
    for i, text in enumerate(corpus):
        with open(f'data_text/doc_{i}.txt', 'w', encoding='utf-8') as f:
            f.write(text)
    print(f'✅ Loaded fallback dataset: {len(corpus)} judgments saved as text files.')

# ==============
# 3) Prepare corpus
# ==============
def clean_text(s):
    s = s.replace('\n', ' ')
    s = re.sub(r'\s+', ' ', s)
    s = re.sub(r'\[[^\]]{1,200}\]', ' ', s)
    return s.strip()

text_files = glob.glob('data_text/*.txt')
corpus = []
for tf in text_files:
    t = open(tf, 'r', encoding='utf-8').read()
    t = clean_text(t)
    if len(t) > 200:
        for i in range(0, min(len(t), 5000), 512):
            chunk = t[i:i+512].strip()
            if len(chunk) > 50:
                corpus.append(chunk)

print('Prepared', len(corpus), 'text chunks.')

# ==============
# 4) Load Legal-GPT (or fallback to GPT-2)
# ==============
model_name = 'lexlms/Legal-GPT'
try:
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(model_name).to('cuda')
except Exception as e:
    print('⚠️ Fallback to GPT-2:', e)
    model_name = 'gpt2'
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(model_name).to('cuda')

model.eval()

# ==============
# 5) Token probability generator
# ==============
def get_next_token_topk(prefix_text, topk=50):
    inputs = tokenizer(prefix_text, return_tensors='pt', truncation=True, max_length=512).to('cuda')
    with torch.no_grad():
        outputs = model(**inputs)
        logits = outputs.logits
    last_logits = logits[0, -1, :]
    probs = torch.softmax(last_logits, dim=-1)
    values, indices = torch.topk(probs, k=topk)
    tokens = tokenizer.convert_ids_to_tokens(indices.tolist())
    return list(zip(tokens, values.cpu().numpy().tolist()))

print(get_next_token_topk('The agreement shall be', topk=10))

# ==============
# 6) Simulate classical vs quantum decoding
# ==============
def classical_beam_search(seq_probs, beam_width=5):
    beams = [('', 1.0)]
    for step_probs in seq_probs:
        new_beams = []
        for seq, score in beams:
            for token, p in step_probs:
                new_beams.append((seq + ' ' + token, score * p))
        beams = sorted(new_beams, key=lambda x: x[1], reverse=True)[:beam_width]
    return beams[0]

def simulated_quantum_runtime(R=50, n=10, k=2.9):
    HR_k = sum([i**(-k) for i in range(1, R+1)])
    HR_k2 = sum([i**(-k/2) for i in range(1, R+1)])
    f = math.log(HR_k2 / (HR_k**0.5)) / math.log(R)
    quantum_runtime = R**(n*f)
    grover_runtime = R**(n*0.5)
    return {'f': f, 'quantum_est': quantum_runtime, 'grover_est': grover_runtime, 'speedup_over_grover': grover_runtime/quantum_runtime}

# Example run
if len(corpus) > 0:
    sample = corpus[0]
    seq_probs = [get_next_token_topk(sample[:100]) for _ in range(5)]
    print('Best classical:', classical_beam_search(seq_probs))
    print('Quantum simulation:', simulated_quantum_runtime(R=50, n=5, k=2.9))

# Plot runtime behavior
k_vals = [1.5, 2.0, 2.5, 3.0, 3.5]
fs = [simulated_quantum_runtime(50,10,k)['f'] for k in k_vals]
plt.plot(k_vals, fs)
plt.title('Quantum speedup exponent f(R,k)')
plt.xlabel('k (power-law exponent)')
plt.ylabel('f(R,k)')
plt.grid(True)
plt.show()

print('\n✅ Notebook ready: automatically loads Indian legal data from AWS or Hugging Face fallback.')

import random, glob
files = glob.glob("data_text/*.txt")
print(open(random.choice(files)).read()[:1000])

"""
Quantum Legal-NLP Experiment (Colab-ready, with automatic dataset fallback)
Adapted for: Colab, English, Legal-GPT, simple quantum simulation

This version automatically falls back to the Hugging Face dataset 'vihaannnn/Indian-Supreme-Court-Judgements-Chunked'
if AWS Open Data (Indian High Court Judgments) is unavailable.
Now includes an interactive test cell for user-supplied judgment paragraphs.
"""

# ==============
# 1) Install dependencies (Colab-friendly)
# ==============
!pip uninstall -y fitz PyMuPDF -q
!pip install --no-cache-dir PyMuPDF -q
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 -q
!pip install awscli boto3 pyarrow transformers[sentencepiece] pdfplumber tqdm datasets matplotlib ipywidgets -q

import os, zipfile, glob, fitz, json, math, re, torch
import matplotlib.pyplot as plt
from tqdm.auto import tqdm
from transformers import AutoTokenizer, AutoModelForCausalLM
from datasets import load_dataset
import ipywidgets as widgets
from IPython.display import display

# ==============
# 2) Try to fetch Indian High Court judgments from AWS, else fallback
# ==============

os.makedirs('data_pdfs', exist_ok=True)
os.makedirs('data_text', exist_ok=True)

try:
    print('Attempting to list AWS Open Data bucket...')
    !aws s3 ls s3://indian-high-court-judgments/data/zip/ --no-sign-request | head -n 5
    !aws s3 cp s3://indian-high-court-judgments/data/zip/year=2023/english_part1.zip ./english_2023_part1.zip --no-sign-request
    if os.path.exists('english_2023_part1.zip'):
        with zipfile.ZipFile('english_2023_part1.zip', 'r') as z:
            z.extractall('data_pdfs')
        print('✅ Extracted AWS dataset into data_pdfs/')
    else:
        raise Exception('AWS zip not found, switching to fallback dataset.')
except Exception as e:
    print('\n⚠️ AWS dataset not accessible, switching to Hugging Face fallback...')
    dataset = load_dataset('vihaannnn/Indian-Supreme-Court-Judgements-Chunked', split='train[:200]')
    corpus = [r['text'] for r in dataset]
    os.makedirs('data_text', exist_ok=True)
    for i, text in enumerate(corpus):
        with open(f'data_text/doc_{i}.txt', 'w', encoding='utf-8') as f:
            f.write(text)
    print(f'✅ Loaded fallback dataset: {len(corpus)} judgments saved as text files.')

# ==============
# 3) Prepare corpus
# ==============
def clean_text(s):
    s = s.replace('\n', ' ')
    s = re.sub(r'\s+', ' ', s)
    s = re.sub(r'\[[^\]]{1,200}\]', ' ', s)
    return s.strip()

text_files = glob.glob('data_text/*.txt')
corpus = []
for tf in text_files:
    t = open(tf, 'r', encoding='utf-8').read()
    t = clean_text(t)
    if len(t) > 200:
        for i in range(0, min(len(t), 5000), 512):
            chunk = t[i:i+512].strip()
            if len(chunk) > 50:
                corpus.append(chunk)

print('Prepared', len(corpus), 'text chunks.')

# ==============
# 4) Load Legal-GPT (or fallback to GPT-2)
# ==============
model_name = 'lexlms/Legal-GPT'
try:
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(model_name).to('cuda')
except Exception as e:
    print('⚠️ Fallback to GPT-2:', e)
    model_name = 'gpt2'
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(model_name).to('cuda')

model.eval()

# ==============
# 5) Token probability generator
# ==============
def get_next_token_topk(prefix_text, topk=50):
    inputs = tokenizer(prefix_text, return_tensors='pt', truncation=True, max_length=512).to('cuda')
    with torch.no_grad():
        outputs = model(**inputs)
        logits = outputs.logits
    last_logits = logits[0, -1, :]
    probs = torch.softmax(last_logits, dim=-1)
    values, indices = torch.topk(probs, k=topk)
    tokens = tokenizer.convert_ids_to_tokens(indices.tolist())
    return list(zip(tokens, values.cpu().numpy().tolist()))

# ==============
# 6) Simulate classical vs quantum decoding
# ==============
def classical_beam_search(seq_probs, beam_width=5):
    beams = [('', 1.0)]
    for step_probs in seq_probs:
        new_beams = []
        for seq, score in beams:
            for token, p in step_probs:
                new_beams.append((seq + ' ' + token, score * p))
        beams = sorted(new_beams, key=lambda x: x[1], reverse=True)[:beam_width]
    return beams[0]

def simulated_quantum_runtime(R=50, n=10, k=2.9):
    HR_k = sum([i**(-k) for i in range(1, R+1)])
    HR_k2 = sum([i**(-k/2) for i in range(1, R+1)])
    f = math.log(HR_k2 / (HR_k**0.5)) / math.log(R)
    quantum_runtime = R**(n*f)
    grover_runtime = R**(n*0.5)
    return {'f': f, 'quantum_est': quantum_runtime, 'grover_est': grover_runtime, 'speedup_over_grover': grover_runtime/quantum_runtime}

# ==============
# 7) Interactive Test Cell
# ==============
print("\n✅ Model ready. Use the text box below to test your own legal paragraph.")

txt_box = widgets.Textarea(
    value='Paste a legal paragraph here...',
    placeholder='Enter judgment text or legal argument...',
    description='Legal Text:',
    layout=widgets.Layout(width='100%', height='200px')
)

def on_click_run(b):
    text = txt_box.value.strip()
    if len(text) < 50:
        print('⚠️ Please enter at least 50 characters of text.')
        return
    print('\nTop predicted tokens:')
    preds = get_next_token_topk(text[:200], topk=10)
    for t, p in preds:
        print(f'{t}\t{p:.5f}')
    seq_probs = [get_next_token_topk(text[:200]) for _ in range(5)]
    best_classical = classical_beam_search(seq_probs)
    quantum_result = simulated_quantum_runtime(R=50, n=5, k=2.9)
    print('\nBest classical decoding:', best_classical)
    print('Quantum simulation:', quantum_result)

run_button = widgets.Button(description='Run Quantum Legal NLP')
run_button.on_click(on_click_run)

display(txt_box, run_button)

# ==============
# 8) Example runtime analysis
# ==============
k_vals = [1.5, 2.0, 2.5, 3.0, 3.5]
fs = [simulated_quantum_runtime(50,10,k)['f'] for k in k_vals]
plt.plot(k_vals, fs)
plt.title('Quantum speedup exponent f(R,k)')
plt.xlabel('k (power-law exponent)')
plt.ylabel('f(R,k)')
plt.grid(True)
plt.show()

print('\n✅ Notebook ready: automatically loads Indian legal data and allows interactive user testing.')

"""
Quantum Legal-NLP Experiment (Colab-ready, with automatic dataset fallback)
Adapted for: Colab, English, Legal-GPT, simple quantum simulation

This version automatically falls back to the Hugging Face dataset 'vihaannnn/Indian-Supreme-Court-Judgements-Chunked'
if AWS Open Data (Indian High Court Judgments) is unavailable.
Now includes an interactive test cell for user-supplied judgment paragraphs with runtime visualization
and downloadable CSV summary of all session results.
"""

# ==============
# 1) Install dependencies (Colab-friendly)
# ==============
!pip uninstall -y fitz PyMuPDF -q
!pip install --no-cache-dir PyMuPDF -q
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 -q
!pip install awscli boto3 pyarrow transformers[sentencepiece] pdfplumber tqdm datasets matplotlib ipywidgets pandas -q

import os, zipfile, glob, fitz, json, math, re, torch, pandas as pd
import matplotlib.pyplot as plt
from tqdm.auto import tqdm
from transformers import AutoTokenizer, AutoModelForCausalLM
from datasets import load_dataset
import ipywidgets as widgets
from IPython.display import display, clear_output

# ==============
# 2) Try to fetch Indian High Court judgments from AWS, else fallback
# ==============

os.makedirs('data_pdfs', exist_ok=True)
os.makedirs('data_text', exist_ok=True)

try:
    print('Attempting to list AWS Open Data bucket...')
    !aws s3 ls s3://indian-high-court-judgments/data/zip/ --no-sign-request | head -n 5
    !aws s3 cp s3://indian-high-court-judgments/data/zip/year=2023/english_part1.zip ./english_2023_part1.zip --no-sign-request
    if os.path.exists('english_2023_part1.zip'):
        with zipfile.ZipFile('english_2023_part1.zip', 'r') as z:
            z.extractall('data_pdfs')
        print('✅ Extracted AWS dataset into data_pdfs/')
    else:
        raise Exception('AWS zip not found, switching to fallback dataset.')
except Exception as e:
    print('\n⚠️ AWS dataset not accessible, switching to Hugging Face fallback...')
    dataset = load_dataset('vihaannnn/Indian-Supreme-Court-Judgements-Chunked', split='train[:200]')
    corpus = [r['text'] for r in dataset]
    os.makedirs('data_text', exist_ok=True)
    for i, text in enumerate(corpus):
        with open(f'data_text/doc_{i}.txt', 'w', encoding='utf-8') as f:
            f.write(text)
    print(f'✅ Loaded fallback dataset: {len(corpus)} judgments saved as text files.')

# ==============
# 3) Prepare corpus
# ==============
def clean_text(s):
    s = s.replace('\n', ' ')
    s = re.sub(r'\s+', ' ', s)
    s = re.sub(r'\[[^\]]{1,200}\]', ' ', s)
    return s.strip()

text_files = glob.glob('data_text/*.txt')
corpus = []
for tf in text_files:
    t = open(tf, 'r', encoding='utf-8').read()
    t = clean_text(t)
    if len(t) > 200:
        for i in range(0, min(len(t), 5000), 512):
            chunk = t[i:i+512].strip()
            if len(chunk) > 50:
                corpus.append(chunk)

print('Prepared', len(corpus), 'text chunks.')

# ==============
# 4) Load Legal-GPT (or fallback to GPT-2)
# ==============
model_name = 'lexlms/Legal-GPT'
try:
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(model_name).to('cuda')
except Exception as e:
    print('⚠️ Fallback to GPT-2:', e)
    model_name = 'gpt2'
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(model_name).to('cuda')

model.eval()

# ==============
# 5) Token probability generator
# ==============
def get_next_token_topk(prefix_text, topk=50):
    inputs = tokenizer(prefix_text, return_tensors='pt', truncation=True, max_length=512).to('cuda')
    with torch.no_grad():
        outputs = model(**inputs)
        logits = outputs.logits
    last_logits = logits[0, -1, :]
    probs = torch.softmax(last_logits, dim=-1)
    values, indices = torch.topk(probs, k=topk)
    tokens = tokenizer.convert_ids_to_tokens(indices.tolist())
    return list(zip(tokens, values.cpu().numpy().tolist()))

# ==============
# 6) Simulate classical vs quantum decoding
# ==============
def classical_beam_search(seq_probs, beam_width=5):
    beams = [('', 1.0)]
    for step_probs in seq_probs:
        new_beams = []
        for seq, score in beams:
            for token, p in step_probs:
                new_beams.append((seq + ' ' + token, score * p))
        beams = sorted(new_beams, key=lambda x: x[1], reverse=True)[:beam_width]
    return beams[0]

def simulated_quantum_runtime(R=50, n=10, k=2.9):
    HR_k = sum([i**(-k) for i in range(1, R+1)])
    HR_k2 = sum([i**(-k/2) for i in range(1, R+1)])
    f = math.log(HR_k2 / (HR_k**0.5)) / math.log(R)
    quantum_runtime = R**(n*f)
    grover_runtime = R**(n*0.5)
    return {'f': f, 'quantum_est': quantum_runtime, 'grover_est': grover_runtime, 'speedup_over_grover': grover_runtime/quantum_runtime}

# ==============
# 7) Interactive Test Cell with Visualization & CSV logging
# ==============
print("\n✅ Model ready. Use the text box below to test your own legal paragraph.")

session_records = []

txt_box = widgets.Textarea(
    value='Paste a legal paragraph here...',
    placeholder='Enter judgment text or legal argument...',
    description='Legal Text:',
    layout=widgets.Layout(width='100%', height='200px')
)

def on_click_run(b):
    clear_output(wait=True)
    display(txt_box, run_button, download_button)
    text = txt_box.value.strip()
    if len(text) < 50:
        print('⚠️ Please enter at least 50 characters of text.')
        return
    print('\nTop predicted tokens:')
    preds = get_next_token_topk(text[:200], topk=10)
    for t, p in preds:
        print(f'{t}\t{p:.5f}')
    seq_probs = [get_next_token_topk(text[:200]) for _ in range(5)]
    best_classical = classical_beam_search(seq_probs)
    quantum_result = simulated_quantum_runtime(R=50, n=5, k=2.9)
    print('\nBest classical decoding:', best_classical)
    print('Quantum simulation:', quantum_result)

    # Visualization
    plt.figure(figsize=(6,4))
    runtimes = [quantum_result['grover_est'], quantum_result['quantum_est']]
    labels = ['Grover', 'Quantum Sim']
    plt.bar(labels, runtimes)
    plt.title('Runtime Comparison (Lower = Faster)')
    plt.ylabel('Estimated Runtime Units')
    plt.grid(True, axis='y', linestyle='--', alpha=0.6)
    plt.show()

    # Log to session records
    session_records.append({
        'text_sample': text[:100] + '...',
        'best_classical': best_classical[0],
        'classical_score': best_classical[1],
        'quantum_f': quantum_result['f'],
        'quantum_est': quantum_result['quantum_est'],
        'grover_est': quantum_result['grover_est'],
        'speedup': quantum_result['speedup_over_grover']
    })

def on_click_download(b):
    if not session_records:
        print('⚠️ No records to download yet.')
        return
    df = pd.DataFrame(session_records)
    df.to_csv('quantum_legal_nlp_results.csv', index=False)
    print('✅ Results saved as quantum_legal_nlp_results.csv. You can download it from Colab files.')

run_button = widgets.Button(description='Run Quantum Legal NLP')
run_button.on_click(on_click_run)

download_button = widgets.Button(description='Download CSV Results')
download_button.on_click(on_click_download)

display(txt_box, run_button, download_button)

# ==============
# 8) Example runtime analysis
# ==============
k_vals = [1.5, 2.0, 2.5, 3.0, 3.5]
fs = [simulated_quantum_runtime(50,10,k)['f'] for k in k_vals]
plt.plot(k_vals, fs)
plt.title('Quantum speedup exponent f(R,k)')
plt.xlabel('k (power-law exponent)')
plt.ylabel('f(R,k)')
plt.grid(True)
plt.show()

print('\n✅ Notebook ready: loads Indian legal data, allows interactive testing, visualizes runtime comparison, and exports CSV summaries.')